# Generated by Django 4.0.6 on 2022-07-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model',
            new_name='Menu',
        ),
    ]
