# Generated by Django 4.0.6 on 2022-07-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_model_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('menu_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu')),
            ],
        ),
    ]
