# Generated by Django 4.0.6 on 2022-07-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category'),
        ),
    ]
