# Generated by Django 4.0.6 on 2022-07-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_menu_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinkCategory',
            new_name='SubCategory',
        ),
    ]
