# Generated by Django 4.0.6 on 2022-07-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_rename_drink_category_menu_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Category'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.subcategory'),
        ),
    ]
