# Generated by Django 4.0.6 on 2022-07-29 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_category_options_alter_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(default='Assign Category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category'),
        ),
    ]
