# Generated by Django 4.0.6 on 2022-08-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_description',
            field=models.TextField(),
        ),
    ]
